DROP TABLE PORTALUSERINFO;
CREATE TABLE PORTALUSERINFO ( USERID VARCHAR2(25) NOT NULL, USERNAME VARCHAR2(50) NOT NULL, PASSWORD VARCHAR2(25) NOT NULL, EMAIL VARCHAR2(50), TEL VARCHAR2(25), NAME VARCHAR2(50) NOT NULL );
insert into PORTALUSERINFO (USERID, USERNAME, PASSWORD, EMAIL, TEL, NAME) values ('1', 'tttt', 'tttttt', 'tt@t.com', '13545945945', '测试测');
insert into PORTALUSERINFO (USERID, USERNAME, PASSWORD, EMAIL, TEL, NAME) values ('21', 'test1', 'test11', 'tt@t.com', '13888888888', '测测');
DROP TABLE SYS_MENU;
CREATE TABLE SYS_MENU ( MENU_ID INTEGER NOT NULL, NAV_ID INTEGER, MENU_TITLE VARCHAR2(50), MENU_CODE VARCHAR2(50), MENU_URL VARCHAR2(500), MENU_SEQ INTEGER, MENU_STATUS INTEGER, MENU_PARENT_ID INTEGER, MENU_NOTE VARCHAR2(255), CONSTRAINT PK_SYS_MENU PRIMARY KEY (MENU_ID) );
COMMENT ON TABLE SYS_MENU IS '树形菜单';
COMMENT ON COLUMN SYS_MENU.MENU_ID IS '菜单id';
COMMENT ON COLUMN SYS_MENU.NAV_ID IS '菜单id';
COMMENT ON COLUMN SYS_MENU.MENU_TITLE IS '菜单标题';
COMMENT ON COLUMN SYS_MENU.MENU_CODE IS '菜单编码';
COMMENT ON COLUMN SYS_MENU.MENU_URL IS '菜单url';
COMMENT ON COLUMN SYS_MENU.MENU_SEQ IS '菜单序号';
COMMENT ON COLUMN SYS_MENU.MENU_STATUS IS '菜单状态:0-停用 1-启用';
COMMENT ON COLUMN SYS_MENU.MENU_PARENT_ID IS '菜单父节点id';
COMMENT ON COLUMN SYS_MENU.MENU_NOTE IS '菜单备注';
insert into SYS_MENU (MENU_ID, NAV_ID, MENU_TITLE, MENU_CODE, MENU_URL, MENU_SEQ, MENU_STATUS, MENU_PARENT_ID, MENU_NOTE) values (525, 203, '用户管理', '02', '/demo/queryPortalUser.action', 1, 1, 0, null);
insert into SYS_MENU (MENU_ID, NAV_ID, MENU_TITLE, MENU_CODE, MENU_URL, MENU_SEQ, MENU_STATUS, MENU_PARENT_ID, MENU_NOTE) values (2, 1, '系统管理', '01', null, 1, 1, 0, null);
insert into SYS_MENU (MENU_ID, NAV_ID, MENU_TITLE, MENU_CODE, MENU_URL, MENU_SEQ, MENU_STATUS, MENU_PARENT_ID, MENU_NOTE) values (3, 1, '系统菜单设置', '0101', '/system/queryNavigatorList.action', 1, 1, 2, null);
CREATE INDEX REFERENCE_1_FK ON SYS_MENU (NAV_ID);
DROP TABLE SYS_NAVIGATOR;
CREATE TABLE SYS_NAVIGATOR ( NAV_ID INTEGER NOT NULL, NAV_NAME VARCHAR2(50), NAV_URL VARCHAR2(500), NAV_SEQ INTEGER, NAV_NOTE VARCHAR2(255), NAV_STATUS INTEGER, CONSTRAINT PK_SYS_NAVIGATOR PRIMARY KEY (NAV_ID) );
COMMENT ON TABLE SYS_NAVIGATOR IS '导航菜单';
COMMENT ON COLUMN SYS_NAVIGATOR.NAV_ID IS '菜单id';
COMMENT ON COLUMN SYS_NAVIGATOR.NAV_NAME IS '菜单名称';
COMMENT ON COLUMN SYS_NAVIGATOR.NAV_URL IS '菜单url';
COMMENT ON COLUMN SYS_NAVIGATOR.NAV_SEQ IS '菜单序号';
COMMENT ON COLUMN SYS_NAVIGATOR.NAV_NOTE IS '菜单备注';
insert into SYS_NAVIGATOR (NAV_ID, NAV_NAME, NAV_URL, NAV_SEQ, NAV_NOTE, NAV_STATUS) values (203, '用户管理DEMO', '/system/main.action', 2, null, 1);
insert into SYS_NAVIGATOR (NAV_ID, NAV_NAME, NAV_URL, NAV_SEQ, NAV_NOTE, NAV_STATUS) values (1, '系统管理', '/system/main.action', 10, null, 1);
ALTER TABLE SYS_MENU ADD CONSTRAINT FK_SYS_MENU_REFERENCE_SYS_NAVI FOREIGN KEY (NAV_ID) REFERENCES SYS_NAVIGATOR (NAV_ID);

--create sequence
CREATE SEQUENCE  SYS_MENU_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 521 CACHE 20 NOORDER  NOCYCLE;

CREATE SEQUENCE  SYS_NAV_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 203 CACHE 20 NOORDER  NOCYCLE;

CREATE SEQUENCE  PORTALUSERINFO_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 203 CACHE 20 NOORDER  NOCYCLE;

